# vim:ts=2:sts=2:sw=2:et
---
sudo: required
language: python
services: docker
python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt

script: cd app && pytest --cov=./app && cd ..

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker build -t ${DOCKER_REPO} .

deploy:
  provider: script
  script: bash ecr_push.sh
  on:
    tags: true
    python: "3.6"
